"""Context + difference pair features (strategy_v2 P3/P4/P5), added on top of a candidate cache.

All statistics are UNSUPERVISED and computed over ALL records of the split being processed
(train for training/val, test for test), per country taken from the data (open set, never a
feature). No labels are used anywhere in this module, so the same code runs unchanged on test.

Groups (each can be switched off for ablation / LOCO checks):
  G1 name uniqueness   how many S1 (and pool records) share the candidate's / the S1's sorted name key
  G2 co-location       same for the sorted full-address key and for (house number + street tokens)
  G3 token edits       extra/missing core tokens typed by rarity (S1 idf), insertion vs substitution,
                       prefix/subset relations, typo-vs-swap (best JW between extra and missing tokens),
                       hand-written business-word flag
  G4 house numbers     digit edit distance, numeric diff, same length, first/last char change,
                       secondary-number conflict, postcode relation
  G5 sibling consensus within the S1's candidate list: do the S1's other name-similar candidates
                       agree with this candidate's house number / name key? (candidate lists must be
                       complete per S1 -> always call on whole S1 groups)

Usage:
    ctx = SplitContext.build("train")                      # ~1 min, a few hundred MB
    X = attach_norm(pairs, "train")                        # pairs: s1_id, cand_id (+ base feats)
    F = add_features(X, ctx)                               # polars, adds float32/int8 columns
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import polars as pl
from rapidfuzz import fuzz, process
from rapidfuzz.distance import JaroWinkler, Levenshtein

from . import paths

NORM_V = 0                               # default normalization cache (ctx v1/v2)
NORM_OF_VER = {1: 0, 2: 0, 3: 1, 4: 1}         # ctx version -> norm cache version (v3 = v2 features on norm_v1:
                                         # learned token map, native-script names transliterated to Latin)


def norm_of(version: int) -> int:
    return NORM_OF_VER.get(version, max(NORM_OF_VER.values()))
GROUPS = ("G1", "G2", "G3", "G4", "G5", "G6")   # G6 only computed for ctx version >= 4
TWIN_MAX = 30           # G6: name keys shared by more S1 than this are too generic to compare addresses
DF_CAP = 50             # v2 token rarity: raw df saturates here (rare tokens keep their df at any density)
CNT_CAP = 20            # counts are capped: test density differs from train (US test S1 ~0.5x)

# Generic "extra business word" list (hand-written, English + French; documented in decisions.md).
# Distractors are generated by appending such words; true copies also get them, so this is only
# one signal among the idf-typed ones.
BIZ_WORDS = frozenset("""
holdings holding group groupe partners partner associates associes services service solutions
enterprises enterprise international global industries industry trading ventures systems center
centre consulting consultants company co corp corporation inc llc ltd limited private pvt public
exports export imports import agency agencies management technologies technology tech labs lab
foundation trust society network networks worldwide america india france national
""".split())

S1_COLS = ["entity_id", "country", "n_core", "a_full", "a_street", "a_house", "a_numbers", "a_postcode"]
C_COLS = ["entity_id", "n_core", "a_full", "a_street", "a_house", "a_numbers", "a_postcode", "a_empty"]


def _norm_file(split: str, source: int, norm_v: int = NORM_V):
    return paths.FEATURE_DIR / f"norm_v{norm_v}_{split}_s{source}.parquet"


def _tokens(col: str) -> pl.Expr:
    return pl.col(col).fill_null("").str.split(" ").list.eval(pl.element().filter(pl.element() != ""))


def key_exprs(prefix: str = "") -> list[pl.Expr]:
    """n_key = sorted core tokens, a_key = sorted a_full tokens, hs_key = house | sorted street tokens.
    Same definition as ber.postrules (n_key/a_key) so rules and features agree."""
    p = prefix
    return [
        _tokens(f"n_core{p}").list.sort().list.join(" ").alias(f"n_key{p}"),
        _tokens(f"a_full{p}").list.sort().list.join(" ").alias(f"a_key{p}"),
        pl.when(pl.col(f"a_house{p}").fill_null("") != "")
          .then(pl.col(f"a_house{p}") + "|" + _tokens(f"a_street{p}").list.sort().list.join(" "))
          .otherwise(pl.lit("")).alias(f"hs_key{p}"),
    ]


@dataclass
class SplitContext:
    """Unsupervised per-split, per-country statistics (all S1 / all pool records of the split)."""
    s1_name: pl.DataFrame    # country, n_key, cnt
    s1_addr: pl.DataFrame    # country, a_key, cnt
    s1_hs: pl.DataFrame      # country, hs_key, cnt
    pool_name: pl.DataFrame  # country, n_key, cnt   (S2+S3 records)
    pool_addr: pl.DataFrame  # country, a_key, cnt
    idf: pl.DataFrame        # country, tok, idf   (log(n_s1 / df) over S1 core names)       [v1 G3]
    df: pl.DataFrame | None = None     # country, tok, df   (#S1 whose core name has the token)  [v2 G3]
    n_s1: pl.DataFrame | None = None   # country, n_s1
    version: int = 1
    s1_twins: pl.DataFrame | None = None  # v4 G6: entity_id, country, n_key, a_full, a_street, a_house of S1 whose
                                          # name key is shared by <= TWIN_MAX S1 (all S1 of the split)

    @classmethod
    def from_frames(cls, s1: pl.DataFrame, pool: pl.DataFrame, version: int = 1) -> "SplitContext":
        """s1: country, n_core, a_full, a_street, a_house; pool: country, n_core, a_full (all records of a split)."""
        keep = ["entity_id"] if "entity_id" in s1.columns else []
        s1 = s1.select(keep + ["country", "n_core", "a_full", "a_street", "a_house"]).with_columns(key_exprs())
        pool = pool.select("country", "n_core", "a_full").with_columns(key_exprs()[:2]).select("country", "n_key", "a_key")
        cnt = lambda df, k: df.filter(pl.col(k) != "").group_by("country", k).len("cnt")  # noqa: E731
        n_s1 = s1.group_by("country").len("n_s1")
        df = (s1.select("country", _tokens("n_core").list.unique().alias("tok")).explode("tok", empty_as_null=True)
                .drop_nulls("tok").group_by("country", "tok").len("df"))
        idf = (df.join(n_s1, on="country")
                 .select("country", "tok", (pl.col("n_s1") / pl.col("df")).log().cast(pl.Float32).alias("idf")))
        twins = None
        if version >= 4 and "entity_id" in s1.columns:
            nk = cnt(s1, "n_key").filter(pl.col("cnt") <= TWIN_MAX).select("country", "n_key")
            twins = s1.join(nk, on=["country", "n_key"]).select("entity_id", "country", "n_key", "a_full", "a_street",
                                                                  "a_house")
        return cls(cnt(s1, "n_key"), cnt(s1, "a_key"), cnt(s1, "hs_key"),
                   cnt(pool, "n_key"), cnt(pool, "a_key"), idf, df, n_s1, version, twins)

    @classmethod
    def build(cls, split: str, version: int = 1, norm_v: int | None = None) -> "SplitContext":
        """norm_v overrides the version's default norm cache (same features on a newer normalization,
        e.g. norm v2 = v1 + France-keyed rules; US/India inputs are byte-identical)."""
        nv = norm_of(version) if norm_v is None else norm_v
        s1 = (pl.scan_parquet(_norm_file(split, 1, nv))
                .select("entity_id", "country", "n_core", "a_full", "a_street", "a_house").collect())
        pool = pl.concat([pl.scan_parquet(_norm_file(split, s, nv)).select("country", "n_core", "a_full").collect()
                          for s in (2, 3)])
        return cls.from_frames(s1, pool, version)

    def max_idf(self) -> pl.DataFrame:
        """idf of an unseen token (df=0 -> treat as df=1) per country."""
        return self.idf.group_by("country").agg(pl.col("idf").max().alias("idf_max"))


def attach_norm(pairs: pl.DataFrame, split: str, norm_v: int = NORM_V) -> pl.DataFrame:
    """Join normalized S1 columns (plain names + country) and candidate columns (suffix _c)."""
    s1_ids = pairs.select(pl.col("s1_id").unique().alias("entity_id"))
    c_ids = pairs.select(pl.col("cand_id").unique().alias("entity_id"))
    s1 = pl.scan_parquet(_norm_file(split, 1, norm_v)).select(S1_COLS).join(s1_ids.lazy(), on="entity_id").collect()
    cs = pl.concat([pl.scan_parquet(_norm_file(split, s, norm_v)).select(C_COLS).join(c_ids.lazy(), on="entity_id").collect()
                    for s in (2, 3)])
    s1 = s1.rename({"entity_id": "s1_id"})
    cs = cs.rename({c: (c + "_c" if c != "entity_id" else "cand_id") for c in cs.columns})
    return pairs.join(s1, on="s1_id", how="left").join(cs, on="cand_id", how="left")


# ----------------------------------------------------------------------------- groups
def _count_feats(X: pl.DataFrame, tbl: pl.DataFrame, key: str, name: str) -> pl.DataFrame:
    """For the candidate's key and the S1's own key: capped count + ==1 flag (0 if key empty)."""
    t = tbl.rename({"cnt": "_n"})
    for side, k in (("c", f"{key}_c"), ("self", key)):
        X = (X.join(t.rename({key: k}), on=["country", k], how="left")
              .with_columns(pl.col("_n").fill_null(0).clip(0, CNT_CAP).cast(pl.Int16).alias(f"{name}_{side}"))
              .drop("_n"))
    return X.with_columns(
        (pl.col(f"{name}_c") == 1).cast(pl.Int8).alias(f"{name}_c_eq1"),
        (pl.col(f"{name}_self") == 1).cast(pl.Int8).alias(f"{name}_self_eq1"),
    )


def g1_name_unique(X: pl.DataFrame, ctx: SplitContext) -> pl.DataFrame:
    X = _count_feats(X, ctx.s1_name, "n_key", "s1_name")
    X = _count_feats(X, ctx.pool_name, "n_key", "pool_name")
    return X.with_columns(((pl.col("n_key") == pl.col("n_key_c")) & (pl.col("n_key") != ""))
                          .cast(pl.Int8).alias("n_key_equal"))


def g2_coloc(X: pl.DataFrame, ctx: SplitContext) -> pl.DataFrame:
    X = _count_feats(X, ctx.s1_addr, "a_key", "s1_addr")
    X = _count_feats(X, ctx.s1_hs, "hs_key", "s1_hs")
    X = _count_feats(X, ctx.pool_addr, "a_key", "pool_addr")
    return X.with_columns(
        ((pl.col("a_key") == pl.col("a_key_c")) & (pl.col("a_key") != "")).cast(pl.Int8).alias("a_key_equal"),
        ((pl.col("hs_key") == pl.col("hs_key_c")) & (pl.col("hs_key") != "")).cast(pl.Int8).alias("hs_key_equal"),
    )


def g3_token_edits(X: pl.DataFrame, ctx: SplitContext, workers: int = -1) -> pl.DataFrame:
    X = X.with_row_index("_r").with_columns(
        _tokens("n_core").list.unique().alias("_ts"), _tokens("n_core_c").list.unique().alias("_tc"))
    X = X.with_columns(pl.col("_tc").list.set_difference("_ts").alias("_ex"),
                       pl.col("_ts").list.set_difference("_tc").alias("_mi"))
    X = X.with_columns(pl.col("_ex").list.len().cast(pl.Int16).alias("ex_n"),
                       pl.col("_mi").list.len().cast(pl.Int16).alias("mi_n"))
    idf = ctx.idf
    imax = ctx.max_idf()

    def tok_stats_v2(col: str, pre: str) -> pl.DataFrame:
        """Density-invariant rarity: raw df (capped) for rare tokens, df/n_s1 only for common tokens,
        explicit unseen-token count (v1 encoded 'unseen' as log(n_s1), which shifts with S1 density)."""
        e = (X.select("_r", "country", pl.col(col).alias("tok")).explode("tok", empty_as_null=True).drop_nulls("tok")
               .join(ctx.df, on=["country", "tok"], how="left").join(ctx.n_s1, on="country", how="left")
               .with_columns(pl.col("df").fill_null(0)))
        common = pl.col("df") >= DF_CAP
        lfrac = (pl.col("df").cast(pl.Float64) / pl.col("n_s1")).log()
        ldf = pl.col("df").clip(0, DF_CAP).cast(pl.Float64).log1p()
        return e.group_by("_r").agg(
            (pl.col("df") == 0).sum().cast(pl.Int16).alias(f"{pre}_unseen_n"),
            ldf.min().cast(pl.Float32).alias(f"{pre}_ldf_min"), ldf.max().cast(pl.Float32).alias(f"{pre}_ldf_max"),
            lfrac.filter(common).max().cast(pl.Float32).alias(f"{pre}_lfrac_cmax"),
            lfrac.filter(common).min().cast(pl.Float32).alias(f"{pre}_lfrac_cmin"),
            pl.col("tok").is_in(list(BIZ_WORDS)).any().cast(pl.Int8).alias(f"{pre}_biz"),
            pl.col("tok").str.contains(r"\d").any().cast(pl.Int8).alias(f"{pre}_digit"),
        )

    def tok_stats(col: str, pre: str) -> pl.DataFrame:
        e = (X.select("_r", "country", pl.col(col).alias("tok")).explode("tok", empty_as_null=True).drop_nulls("tok")
               .join(idf, on=["country", "tok"], how="left").join(imax, on="country", how="left")
               .with_columns(pl.col("idf").fill_null(pl.col("idf_max")).fill_null(15.0)))
        return e.group_by("_r").agg(
            pl.col("idf").max().alias(f"{pre}_idf_max"), pl.col("idf").min().alias(f"{pre}_idf_min"),
            pl.col("idf").sum().alias(f"{pre}_idf_sum"),
            pl.col("tok").is_in(list(BIZ_WORDS)).any().cast(pl.Int8).alias(f"{pre}_biz"),
            pl.col("tok").str.contains(r"\d").any().cast(pl.Int8).alias(f"{pre}_digit"),
        )

    ts = tok_stats_v2 if ctx.version >= 2 else tok_stats
    X = X.join(ts("_ex", "ex"), on="_r", how="left").join(ts("_mi", "mi"), on="_r", how="left")
    # typo vs substitution: best JW between any extra and any missing token (only rows with both)
    both = X.filter((pl.col("ex_n") > 0) & (pl.col("mi_n") > 0)).select("_r", "_ex", "_mi")
    if both.height:
        cr = both.explode("_ex", empty_as_null=True).explode("_mi", empty_as_null=True)
        jw = process.cpdist(cr["_ex"].to_list(), cr["_mi"].to_list(), scorer=JaroWinkler.normalized_similarity,
                            workers=workers, dtype=np.float32)
        best = cr.select("_r").with_columns(pl.Series("sub_jw", jw)).group_by("_r").agg(pl.col("sub_jw").max())
        X = X.join(best, on="_r", how="left")
    else:
        X = X.with_columns(pl.lit(None, dtype=pl.Float32).alias("sub_jw"))
    s, c = pl.col("n_core").fill_null(""), pl.col("n_core_c").fill_null("")
    X = X.with_columns(
        pl.col("sub_jw").fill_null(-1.0).cast(pl.Float32),
        # edit type: 0 same set, 1 pure insertion (cand adds), 2 pure deletion, 3 substitution
        pl.when((pl.col("ex_n") == 0) & (pl.col("mi_n") == 0)).then(0)
          .when(pl.col("mi_n") == 0).then(1).when(pl.col("ex_n") == 0).then(2).otherwise(3)
          .cast(pl.Int8).alias("edit_type"),
        ((s != "") & c.str.starts_with(s + " ")).cast(pl.Int8).alias("s1_prefix_of_c"),
        ((c != "") & s.str.starts_with(c + " ")).cast(pl.Int8).alias("c_prefix_of_s1"),
        (pl.col("_ts").list.first() == pl.col("_tc").list.first()).fill_null(False).cast(pl.Int8).alias("first_tok_eq"),
    )
    if ctx.version >= 2:      # rows without extra/missing tokens: counts 0, ldf -1; lfrac stays null (NaN)
        fill = {f"{p}_{k}": -1.0 for p in ("ex", "mi") for k in ("ldf_min", "ldf_max")}
        X = X.with_columns([pl.col(f"{p}_unseen_n").fill_null(0).cast(pl.Int16) for p in ("ex", "mi")])
    else:
        fill = {f"{p}_{k}": 0.0 for p in ("ex", "mi") for k in ("idf_max", "idf_min", "idf_sum")}
    X = X.with_columns([pl.col(k).fill_null(v).cast(pl.Float32) for k, v in fill.items()] +
                       [pl.col(f"{p}_{k}").fill_null(0).cast(pl.Int8) for p in ("ex", "mi") for k in ("biz", "digit")])
    return X.drop("_r", "_ts", "_tc", "_ex", "_mi")


def g4_house(X: pl.DataFrame, workers: int = -1) -> pl.DataFrame:
    h, hc = pl.col("a_house").fill_null(""), pl.col("a_house_c").fill_null("")
    both = (h != "") & (hc != "")
    lev = process.cpdist(X["a_house"].fill_null("").to_list(), X["a_house_c"].fill_null("").to_list(),
                         scorer=Levenshtein.distance, workers=workers, dtype=np.int32)
    n1 = h.str.extract(r"(\d{1,9})", 1).cast(pl.Int64, strict=False)
    n2 = hc.str.extract(r"(\d{1,9})", 1).cast(pl.Int64, strict=False)
    X = X.with_columns(pl.Series("_lev", lev))
    # secondary numbers = a_numbers tokens other than the house token
    sec = lambda col, hcol: _tokens(col).list.set_difference(pl.concat_list(pl.col(hcol).fill_null("")))  # noqa: E731
    X = X.with_columns(sec("a_numbers", "a_house").alias("_s1"), sec("a_numbers_c", "a_house_c").alias("_s2"))
    inter = pl.col("_s1").list.set_intersection("_s2").list.len()
    union = pl.col("_s1").list.set_union("_s2").list.len()
    pc, pcc = pl.col("a_postcode").fill_null(""), pl.col("a_postcode_c").fill_null("")
    X = X.with_columns(
        pl.when(both).then(pl.col("_lev")).otherwise(-1).cast(pl.Int16).alias("house_lev"),
        pl.when(both).then((n1 - n2).abs().cast(pl.Float32).log1p()).otherwise(-1.0)
          .fill_null(-1.0).cast(pl.Float32).alias("house_logdiff"),
        pl.when(both).then((n1 - n2).abs().cast(pl.Float32) / pl.max_horizontal(n1, n2, 1).cast(pl.Float32))
          .otherwise(-1.0).fill_null(-1.0).cast(pl.Float32).alias("house_reldiff"),
        pl.when(both).then((h.str.len_chars() == hc.str.len_chars()).cast(pl.Int8)).otherwise(-1)
          .cast(pl.Int8).alias("house_same_len"),
        pl.when(both).then((h.str.slice(0, 1) != hc.str.slice(0, 1)).cast(pl.Int8)).otherwise(-1)
          .cast(pl.Int8).alias("house_first_diff"),
        pl.when(both).then((h.str.slice(-1, 1) != hc.str.slice(-1, 1)).cast(pl.Int8)).otherwise(-1)
          .cast(pl.Int8).alias("house_last_diff"),
        # -1 no secondary numbers anywhere, 0 one side only, 1 overlap, 2 both present & disjoint
        pl.when(union == 0).then(-1)
          .when((pl.col("_s1").list.len() == 0) | (pl.col("_s2").list.len() == 0)).then(0)
          .when(inter > 0).then(1).otherwise(2).cast(pl.Int8).alias("sec_num_rel"),
        pl.when((pc == "") & (pcc == "")).then(0).when(pc == pcc).then(1)
          .when((pc == "") | (pcc == "")).then(2).otherwise(3).cast(pl.Int8).alias("postcode_rel"),
    )
    return X.drop("_lev", "_s1", "_s2")


def g5_siblings(X: pl.DataFrame, name_col: str = "name_tset", sib_min: float = 80.0) -> pl.DataFrame:
    """Leave-one-out consensus among the S1's other name-similar candidates (proxy for its true copies).
    Requires complete candidate lists per S1."""
    hc = pl.col("a_house_c").fill_null("")
    X = X.with_columns(((pl.col(name_col) >= sib_min) & (hc != "")).alias("_sib"))
    sib = pl.col("_sib").cast(pl.Int16)
    X = X.with_columns(
        sib.sum().over("s1_id").alias("_nsib"),
        sib.sum().over(["s1_id", "a_house_c"]).alias("_nsib_h"),                   # sibs with my house
        (sib * (hc == pl.col("a_house").fill_null("")).cast(pl.Int16)).sum().over("s1_id").alias("_nsib_s1h"),
        pl.len().over(["s1_id", "n_key_c"]).alias("_nkey"),                         # cands with my name key
    )
    me = sib                                                                      # remove self (leave-one-out)
    me_s1h = sib * (hc == pl.col("a_house").fill_null("")).cast(pl.Int16)
    X = X.with_columns(
        (pl.col("_nsib") - me).clip(0, CNT_CAP).cast(pl.Int16).alias("sib_n"),
        pl.when(hc != "").then(pl.col("_nsib_h") - me).otherwise(-1).clip(-1, CNT_CAP).cast(pl.Int16)
          .alias("sib_house_agree"),
        (pl.col("_nsib_s1h") - me_s1h).clip(0, CNT_CAP).cast(pl.Int16).alias("sib_s1house_agree"),
        (pl.col("_nkey") - 1).clip(0, CNT_CAP).cast(pl.Int16).alias("sib_namekey_same"),
    )
    X = X.with_columns(
        pl.when(pl.col("sib_n") > 0).then(pl.col("sib_house_agree").clip(0, None) / pl.col("sib_n"))
          .otherwise(-1.0).cast(pl.Float32).alias("sib_house_frac"),
        pl.when(pl.col("sib_n") > 0).then(pl.col("sib_s1house_agree") / pl.col("sib_n"))
          .otherwise(-1.0).cast(pl.Float32).alias("sib_s1house_frac"),
    )
    return X.drop("_sib", "_nsib", "_nsib_h", "_nsib_s1h", "_nkey")


def g6_twins(X: pl.DataFrame, ctx: SplitContext, workers: int = -1) -> pl.DataFrame:
    """Name-twin competition: the OTHER S1 of the split sharing the candidate's exact name key. Does one of them fit
    the candidate's address better than this S1? (A templated same-name record on a different street belongs to its
    twin, not to us.) Computed over ALL S1 of the split -> identical meaning on val (mini queries) and test."""
    X = X.with_row_index("_r")
    T = ctx.s1_twins.rename({"entity_id": "_tid", "n_key": "n_key_c", "a_full": "_ta", "a_street": "_ts",
                             "a_house": "_th"})
    J = (X.select("_r", "s1_id", "country", "n_key_c", "a_full_c", "a_street_c", "a_house_c")
          .filter(pl.col("n_key_c") != "")
          .join(T, on=["country", "n_key_c"]).filter(pl.col("_tid") != pl.col("s1_id")))
    W = dict(workers=workers, dtype=np.float32)
    if J.height:
        J = J.with_columns(
            pl.Series("_asim", process.cpdist(J["_ta"].fill_null("").to_list(), J["a_full_c"].fill_null("").to_list(),
                                              scorer=fuzz.token_set_ratio, **W)),
            pl.Series("_ssim", process.cpdist(J["_ts"].fill_null("").to_list(), J["a_street_c"].fill_null("").to_list(),
                                              scorer=fuzz.token_set_ratio, **W)),
            # strict whole-string street similarity: templated FR twins share the number and generic street words
            # (rue/des/avenue) but differ in the street NAME, which token overlap hides
            pl.Series("_ssr", process.cpdist(J["_ts"].fill_null("").to_list(), J["a_street_c"].fill_null("").to_list(),
                                             scorer=fuzz.ratio, **W)),
            ((pl.col("_th").fill_null("") == pl.col("a_house_c").fill_null("")) & (pl.col("_th").fill_null("") != ""))
            .alias("_heq"))
        A = J.group_by("_r").agg(pl.len().cast(pl.Int16).alias("twin_n"), pl.col("_asim").max().alias("twin_addr_best"),
                                 pl.col("_ssim").max().alias("twin_street_best"),
                                 pl.col("_ssr").max().alias("twin_sratio_best"),
                                 pl.col("_ssr").filter(pl.col("_heq")).max().alias("_hs_sratio"),
                                 pl.col("_heq").any().cast(pl.Int8).alias("twin_house_eq"))
        X = X.join(A, on="_r", how="left")
    else:
        X = X.with_columns(pl.lit(None, pl.Int16).alias("twin_n"), pl.lit(None, pl.Float32).alias("twin_addr_best"),
                           pl.lit(None, pl.Float32).alias("twin_street_best"), pl.lit(None, pl.Float32).alias("twin_sratio_best"),
                           pl.lit(None, pl.Float32).alias("_hs_sratio"), pl.lit(None, pl.Int8).alias("twin_house_eq"))
    own_a = process.cpdist(X["a_full"].fill_null("").to_list(), X["a_full_c"].fill_null("").to_list(),
                           scorer=fuzz.token_set_ratio, **W)
    own_s = process.cpdist(X["a_street"].fill_null("").to_list(), X["a_street_c"].fill_null("").to_list(),
                           scorer=fuzz.token_set_ratio, **W)
    own_r = process.cpdist(X["a_street"].fill_null("").to_list(), X["a_street_c"].fill_null("").to_list(),
                           scorer=fuzz.ratio, **W)
    X = X.with_columns(pl.Series("_own_a", own_a), pl.Series("_own_s", own_s), pl.Series("_own_r", own_r))
    has = pl.col("twin_n").fill_null(0) > 0
    return X.with_columns(
        pl.col("twin_n").fill_null(0).cast(pl.Int16),
        pl.col("twin_house_eq").fill_null(0).cast(pl.Int8),
        # >0: this S1 fits the candidate's address better than every twin; <0: some twin fits better. NaN: no twin.
        pl.when(has).then(pl.col("_own_a") - pl.col("twin_addr_best")).otherwise(None).cast(pl.Float32)
          .alias("twin_addr_margin"),
        pl.when(has).then(pl.col("_own_s") - pl.col("twin_street_best")).otherwise(None).cast(pl.Float32)
          .alias("twin_street_margin"),
        pl.when(has).then(pl.col("_own_r") - pl.col("twin_sratio_best")).otherwise(None).cast(pl.Float32)
          .alias("twin_street_ratio_margin"),
        # a twin has the candidate's house number AND a better street-name fit than this S1 (templated-twin FP)
        (pl.col("_hs_sratio").fill_null(-1.0) > pl.col("_own_r")).cast(pl.Int8).alias("twin_hs_better"),
        pl.col("twin_addr_best").cast(pl.Float32),
        # the key was too generic to compare (more than TWIN_MAX S1 share the candidate's name key)
        pl.lit(0, pl.Int8).alias("twin_generic"),
    ).drop("_r", "_own_a", "_own_s", "_own_r", "twin_street_best", "twin_sratio_best", "_hs_sratio")


def add_features(X: pl.DataFrame, ctx: SplitContext, groups=GROUPS, workers: int = -1) -> pl.DataFrame:
    """X = attach_norm(pairs) (+ base features incl. name_tset for G5). Returns X + new feature columns."""
    X = X.with_columns(key_exprs() + key_exprs("_c"))
    if "G1" in groups:
        X = g1_name_unique(X, ctx)
    if "G2" in groups:
        X = g2_coloc(X, ctx)
    if "G3" in groups:
        X = g3_token_edits(X, ctx, workers)
    if "G4" in groups:
        X = g4_house(X, workers)
    if "G5" in groups:
        X = g5_siblings(X)
    if "G6" in groups and ctx.version >= 4:
        X = g6_twins(X, ctx, workers)
        raw = ctx.s1_name.rename({"n_key": "n_key_c", "cnt": "_raw"})       # uncapped S1 count of the name key
        X = (X.join(raw, on=["country", "n_key_c"], how="left")
              .with_columns((pl.col("_raw").fill_null(0) > TWIN_MAX).cast(pl.Int8).alias("twin_generic")).drop("_raw"))
    return X


# Derived (coarsened) features: new name -> (source column, quantum). Computed from the saved raw column at load time
# by every consumer (training, orphan_sim, test rescoring), so they can never disagree. lfrac q05 = log(df/n_s1) rounded
# to 0.5: the raw value acts as a token-identity code and is brittle to S1 pruning/density (EXP-A, 26 Sep).
DERIVED = {f"{p}_lfrac_{k}_q05": (f"{p}_lfrac_{k}", 0.5) for p in ("ex", "mi") for k in ("cmax", "cmin")}


# Per-source competition features (G7 "ps", monitor note 11): computed per S1 over its COMPLETE candidate list,
# separately for each candidate source (S2 vs S3), from existing pair scores. Group-level, so every consumer must pass
# whole S1 groups (all do: caches and test batches hold complete S1 candidate lists).
PS_KEYS = ("name_tset", "addr_tset", "cos_na")
PS_FEATS = ([f"ps_rank_{k}" for k in PS_KEYS] + [f"ps_gap_{k}" for k in PS_KEYS] +
            ["ps_n90_name_tset", "ps_n90_addr_tset", "ps_n_src", "xs_max_name_tset", "xs_max_addr_tset"])
PS_SRC = ["s1_id", "cand_src", *PS_KEYS]


EMB_FEATS = ["emb_cos_name", "emb_cos_addr", "emb_cos_full"]   # Lane B: frozen bge-m3 band cosines (NaN outside band)


def join_emb(X: pl.DataFrame, cache: str, tag: str, feats: list[str]) -> pl.DataFrame:
    """Left-join the band cosines data/cands/<cache>/emb_<tag>.parquet (s1_id, cand_id, emb_cos_*) when requested."""
    need = [f for f in EMB_FEATS if f in feats and f not in X.columns]
    if not need:
        return X
    E = pl.read_parquet(paths.DATA_DIR / "cands" / cache / f"emb_{tag}.parquet", columns=["s1_id", "cand_id"] + need)
    return X.join(E, on=["s1_id", "cand_id"], how="left")


def expand_derived(feats: list[str]) -> list[str]:
    """Feature list with derived names replaced by their source columns (dedup, order kept)."""
    out = []
    for f in feats:
        if f in DERIVED:
            out.append(DERIVED[f][0])
        elif f in PS_FEATS:
            out.extend(PS_SRC)
        elif f in EMB_FEATS:                     # joined from emb_<tag>.parquet, not a cache column
            continue
        else:
            out.append(f)
    return list(dict.fromkeys(out))


def _add_ps(X: pl.DataFrame) -> pl.DataFrame:
    g = ["s1_id", "cand_src"]
    X = X.with_columns([pl.col(k).fill_null(-1.0).cast(pl.Float32).alias(f"_{k}") for k in PS_KEYS])
    X = X.with_columns(
        [pl.col(f"_{k}").rank("min", descending=True).over(g).cast(pl.Int16).alias(f"ps_rank_{k}") for k in PS_KEYS] +
        [(pl.col(f"_{k}").max().over(g) - pl.col(f"_{k}")).cast(pl.Float32).alias(f"ps_gap_{k}") for k in PS_KEYS] +
        [(pl.col(f"_{k}") >= 90).sum().over(g).cast(pl.Int16).alias(f"ps_n90_{k}") for k in ("name_tset", "addr_tset")] +
        [pl.len().over(g).cast(pl.Int16).alias("ps_n_src")])
    mx = X.group_by(g).agg([pl.col(f"_{k}").max().alias(f"xs_max_{k}") for k in ("name_tset", "addr_tset")]) \
          .with_columns((1 - pl.col("cand_src")).cast(X.schema["cand_src"]).alias("cand_src"))   # other source's best
    X = X.join(mx, on=g, how="left").with_columns([pl.col(f"xs_max_{k}").fill_null(-1.0).cast(pl.Float32)
                                                   for k in ("name_tset", "addr_tset")])
    return X.drop([f"_{k}" for k in PS_KEYS])


def add_derived(X: pl.DataFrame, feats: list[str]) -> pl.DataFrame:
    add = [(pl.col(DERIVED[f][0]) / DERIVED[f][1]).round(0) * DERIVED[f][1] for f in feats if f in DERIVED]
    names = [f for f in feats if f in DERIVED]
    if add:
        X = X.with_columns([e.cast(pl.Float32).alias(n) for e, n in zip(add, names)])
    if any(f in PS_FEATS for f in feats) and "ps_n_src" not in X.columns:
        X = _add_ps(X)
    return X


NORM_COLS = [c for c in S1_COLS if c != "entity_id"] + [c + "_c" for c in C_COLS if c != "entity_id"] + \
            ["n_key", "a_key", "hs_key", "n_key_c", "a_key_c", "hs_key_c"]


def new_feature_cols(F: pl.DataFrame, base: list[str]) -> list[str]:
    skip = set(NORM_COLS) | set(base) | {"s1_id", "cand_id", "label", "role", "country"}
    return [c for c in F.columns if c not in skip]
